meta_product_name: "Control+"
meta_title: "Control+ | Controle Sua Vida"
meta_description: "Faça a gestão de tarefas da forma mais eficiente para a sua rotina. Gerencie com precisão todas as despesas dos seus cartões de crédito, contas de bancos."
meta_image: "finances1.jpg" # should exist in `app/assets/images/`
